export const initialState = {
    user: null,
    artists: null,
    songs: null,
    songIndex: 0,
    songsWait: null,
    isSongPlaying: false,
    songWaitPlaylist:null,
    songsLike:[],
    allPlaylist:null,
    allPlaylistsOfMe:[],
    currentPlaylist:null,
    positionX:null,
    positionY:null,
    songInfo:null,
    allSongAd:null,
    relateTrack:null,
    nameArtist:null,
    isOpenInfoTrack:false,
    isOwnerPlaylist:false,
    idPlaylistCurrent:null,
    textSearch:null,
  };